r"""Generate lean_status.tex: parse SubspaceOverlap.lean, emit theorem-status
macros and a status table.

For each `theorem` / `lemma` / `def` declaration, detect whether the body
contains `sorry`. Emit macros so main.tex can say
"Theorem \thmStatOf{stableRank_smul_invariant}" and the current status
flips automatically when the Lean file changes.

Three-way classification (authoritative definitions):
  (a) PROVEN  — theorem/lemma with a real proof body; no sorry at all.
                 → \leanProvenCount, status marker \proofCheck
  (b) STUB    — top-level `theorem foo : True := sorry` placeholders.
                 Literature-terminology stubs; statement is trivially True,
                 proof is just sorry.  These are NOT claims about math — they
                 name concepts for downstream work.
                 → \leanSorryCount (= stub count), status marker \proofStub
  (c) DEFERRED — theorem with a real (non-True) mathematical statement but
                 the entire proof body is a bare `sorry`.  These are honest
                 gaps in load-bearing proofs with known proof sketches.
                 → \leanInProofSorryCount, status marker \proofSorry

Note: \leanSorryCount counts category (b) stubs, NOT category (c) deferred
proofs.  This matches the prose in main.tex ("sorry stubs mark
literature-terminology placeholders").  Category (c) is separately reported
via \leanInProofSorryCount so reviewers see the honest gap count.
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
LEAN = HERE.parent / "lean" / "SubspaceOverlap.lean"


def parse(src: str) -> list[dict]:
    """Extract (kind, name, has_sorry) for each top-level declaration.
    Heuristic: look for 'theorem X', 'lemma X', 'def X', 'noncomputable def X';
    the declaration extends to the next such keyword or end of file.
    """
    # Tokenize by declaration starts
    pattern = re.compile(
        r"^(?:noncomputable\s+)?(theorem|lemma|def)\s+([A-Za-z_][A-Za-z0-9_']*)",
        re.MULTILINE,
    )
    matches = list(pattern.finditer(src))
    out = []
    for i, m in enumerate(matches):
        kind, name = m.group(1), m.group(2)
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(src)
        body = src[start:end]
        # Detect sorry — but only if it appears as a statement, not in comments/strings.
        # Simple heuristic: strip line comments, then search for "sorry".
        body_code = re.sub(r"--[^\n]*", "", body)
        # Strip block comments (/- ... -/)
        body_code = re.sub(r"/-.*?-/", "", body_code, flags=re.DOTALL)
        has_sorry = bool(re.search(r"\bsorry\b", body_code))
        # Detect True-sorry stubs (trivial theorem placeholders)
        is_true_stub = bool(re.search(r":\s*True\s*:=\s*sorry", body_code))
        out.append({
            "kind": kind,
            "name": name,
            "has_sorry": has_sorry,
            "is_true_stub": is_true_stub,
        })
    return out


src = LEAN.read_text()
decls = parse(src)


def tex_name(name: str) -> str:
    """Convert snake_case to CamelCase for LaTeX macro names.
    Preserve existing camelCase within each underscore-separated segment:
    `frobeniusSq` → `FrobeniusSq` (not `Frobeniussq`)."""
    return "thmStatOf" + "".join(w[:1].upper() + w[1:] for w in name.split("_"))


# Emit per-theorem status macros
lines = [
    "% Auto-generated by generate_lean_status.py — DO NOT EDIT",
    "% Regenerate: make lean-status",
    "",
    "\\newcommand{\\proofCheck}{\\ensuremath{\\checkmark}}",
    "\\newcommand{\\proofSorry}{\\textsc{sorry}}",
    "\\newcommand{\\proofStub}{\\textsc{stub}}",
    "",
]

proven_count = 0          # (a) real proofs
in_proof_sorry_count = 0  # (c) non-True statements with bare := sorry
stub_count = 0            # (b) True := sorry placeholders

for d in decls:
    if d["kind"] in ("theorem", "lemma"):
        if d["is_true_stub"]:
            # (b) literature-terminology stub: `theorem foo : True := sorry`
            status_macro = "\\proofStub"
            stub_count += 1
        elif d["has_sorry"]:
            # (c) real mathematical statement, proof body deferred via sorry
            status_macro = "\\proofSorry"
            in_proof_sorry_count += 1
        else:
            # (a) complete proof, no sorry
            status_macro = "\\proofCheck"
            proven_count += 1
        lines.append(f"\\newcommand{{\\{tex_name(d['name'])}}}{{{status_macro}}}")

lines += [
    "",
    f"% (a) theorems/lemmas with complete proofs (no sorry)",
    f"\\newcommand{{\\leanProvenCount}}{{{proven_count}}}",
    f"% (b) True := sorry stubs — literature-terminology placeholders",
    f"% NOTE: \\leanSorryCount = stub count (b), matching main.tex prose",
    f"\\newcommand{{\\leanSorryCount}}{{{stub_count}}}",
    f"% (c) real statements with deferred proof body (honest load-bearing gaps)",
    f"\\newcommand{{\\leanInProofSorryCount}}{{{in_proof_sorry_count}}}",
    f"% backward-compat alias (same as \\leanSorryCount)",
    f"\\newcommand{{\\leanStubCount}}{{{stub_count}}}",
    f"\\newcommand{{\\leanDefCount}}{{{sum(1 for d in decls if d['kind']=='def')}}}",
    "",
]


# Emit a status table
lines += [
    "% Lean theorem status table",
    "\\begin{table}[h]",
    "  \\centering",
    "  \\caption{Formally verified theorems in",
    "  \\texttt{LeanMining/NeuralGeometry/SubspaceOverlap.lean}"
    " (Lean 4 + Mathlib). Three-way status:"
    " $\\proofCheck$ = complete proof (no \\texttt{sorry});"
    " $\\proofSorry$ = real mathematical statement with deferred proof body"
    " (honest load-bearing gap, known proof sketch exists);"
    " $\\proofStub$ = \\texttt{True := sorry} literature-terminology"
    " placeholder (not a mathematical claim, names a concept for downstream"
    " work). Counts: \\leanProvenCount~proven,"
    " \\leanInProofSorryCount~deferred, \\leanSorryCount~stubs.}",
    "  \\label{tab:lean-status}",
    "  \\small",
    "  \\begin{tabular}{ll}",
    "    \\toprule",
    "    Theorem / Lemma & Status \\\\",
    "    \\midrule",
]
for d in decls:
    if d["kind"] not in ("theorem", "lemma"):
        continue
    stat = "\\proofStub" if d["is_true_stub"] else ("\\proofSorry" if d["has_sorry"] else "\\proofCheck")
    # escape underscores for display
    disp = d["name"].replace("_", "\\_")
    lines.append(f"    \\texttt{{{disp}}} & {stat} \\\\")
lines += [
    "    \\bottomrule",
    "  \\end{tabular}",
    "\\end{table}",
]

(HERE / "lean_status.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {HERE / 'lean_status.tex'}")
print(f"  proven (a): {proven_count}, deferred/in-proof sorry (c): {in_proof_sorry_count}, stubs/True-sorry (b): {stub_count}")
