r"""Generate lean_status.tex: parse SubspaceOverlap.lean, emit theorem-status
macros and a status table.

For each `theorem` / `lemma` / `def` declaration, detect whether the body
contains `sorry`. Emit macros so main.tex can say
"Theorem \thmStatOf{stableRank_smul_invariant}" and the current status
flips automatically when the Lean file changes.

Three-way classification (authoritative definitions):
  (a) PROVEN  — theorem/lemma with a real proof body; no sorry at all.
                 → \leanProvenCount, status marker \proofCheck
  (b) STUB    — top-level `theorem foo : True := sorry` placeholders.
                 Literature-terminology stubs; statement is trivially True,
                 proof is just sorry.  These are NOT claims about math — they
                 name concepts for downstream work.
                 → \leanSorryCount (= stub count), status marker \proofStub
  (c) DEFERRED — theorem with a real (non-True) mathematical statement but
                 the entire proof body is a bare `sorry`.  These are honest
                 gaps in load-bearing proofs with known proof sketches.
                 → \leanInProofSorryCount, status marker \proofSorry

Note: \leanSorryCount counts category (b) stubs, NOT category (c) deferred
proofs.  This matches the prose in main.tex ("sorry stubs mark
literature-terminology placeholders").  Category (c) is separately reported
via \leanInProofSorryCount so reviewers see the honest gap count.
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
# Vendored Lean source lives in the public paper repo at
# lean/LeanMining/NeuralGeometry/SubspaceOverlap.lean. Prefer it so the
# script runs standalone inside the public repo. Fall back to the monorepo
# canonical only if the vendored copy is missing (e.g. a fresh clone before
# `make sync-lean` has run).
LOCAL_LEAN = HERE.parent / "lean" / "LeanMining" / "NeuralGeometry" / "SubspaceOverlap.lean"
CANONICAL_LEAN = HERE.parents[2] / "LeanMining" / "NeuralGeometry" / "SubspaceOverlap.lean"
LEAN = LOCAL_LEAN if LOCAL_LEAN.exists() else CANONICAL_LEAN


def parse(src: str) -> list[dict]:
    """Extract (kind, name, has_sorry) for each top-level declaration.
    Heuristic: look for 'theorem X', 'lemma X', 'def X', 'noncomputable def X';
    the declaration extends to the next such keyword or end of file.
    """
    # Tokenize by declaration starts
    pattern = re.compile(
        r"^(?:noncomputable\s+)?(theorem|lemma|def)\s+([A-Za-z_][A-Za-z0-9_']*)",
        re.MULTILINE,
    )
    matches = list(pattern.finditer(src))
    out = []
    for i, m in enumerate(matches):
        kind, name = m.group(1), m.group(2)
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(src)
        body = src[start:end]
        # Preceding comment block — detect WEAKENING NOTE attached to THIS decl.
        # Scan only the text between the previous decl end and this decl start,
        # then take the last block-comment (/- ... -/ or /-- ... -/) in that slice.
        prev_end = matches[i - 1].end() if i > 0 else 0
        between = src[prev_end:m.start()]
        # Find last block comment in `between`
        block_comments = list(re.finditer(r"/-(?:-)?.*?-/", between, re.DOTALL))
        is_partial = False
        if block_comments:
            last_block = block_comments[-1].group(0)
            is_partial = "WEAKENING NOTE" in last_block
        # Detect sorry — but only if it appears as a statement, not in comments/strings.
        body_code = re.sub(r"--[^\n]*", "", body)
        body_code = re.sub(r"/-.*?-/", "", body_code, flags=re.DOTALL)
        has_sorry = bool(re.search(r"\bsorry\b", body_code))
        is_true_stub = bool(re.search(r":\s*True\s*:=\s*sorry", body_code))
        out.append({
            "kind": kind,
            "name": name,
            "has_sorry": has_sorry,
            "is_true_stub": is_true_stub,
            "is_partial": is_partial,
        })
    return out


src = LEAN.read_text()
decls = parse(src)


def tex_name(name: str) -> str:
    """Convert snake_case to CamelCase for LaTeX macro names.
    Preserve existing camelCase within each underscore-separated segment:
    `frobeniusSq` → `FrobeniusSq` (not `Frobeniussq`)."""
    return "thmStatOf" + "".join(w[:1].upper() + w[1:] for w in name.split("_"))


# Emit per-theorem status macros
lines = [
    "% Auto-generated by generate_lean_status.py — DO NOT EDIT",
    "% Regenerate: make lean-status",
    "",
    "\\newcommand{\\proofCheck}{\\ensuremath{\\checkmark}}",
    "\\newcommand{\\proofSorry}{\\textsc{sorry}}",
    "\\newcommand{\\proofStub}{\\textsc{stub}}",
    "\\newcommand{\\proofPartial}{\\textsc{partial}}",
    "",
]

proven_count = 0          # (a) real proofs of the full claim
partial_count = 0         # (d) proof of a weakened statement (WEAKENING NOTE present)
in_proof_sorry_count = 0  # (c) non-True statements with bare := sorry
stub_count = 0            # (b) True := sorry placeholders

for d in decls:
    if d["kind"] in ("theorem", "lemma"):
        if d["is_true_stub"]:
            status_macro = "\\proofStub"
            stub_count += 1
        elif d["has_sorry"]:
            status_macro = "\\proofSorry"
            in_proof_sorry_count += 1
        elif d["is_partial"]:
            # (d) weakened statement proved — original paper claim not formalized
            status_macro = "\\proofPartial"
            partial_count += 1
        else:
            status_macro = "\\proofCheck"
            proven_count += 1
        lines.append(f"\\newcommand{{\\{tex_name(d['name'])}}}{{{status_macro}}}")

# ── Paper-facing sorry disclosure ───────────────────────────────────────────
# Five sorries that appear (directly or indirectly) in paper claims.
# Each entry: (lean_name, paper_section, provability_class, note)
#   provability_class:
#     "planned"      — provable with known proof sketch; formal proof queued
#     "empirical"    — empirical/statistical claim; not Lean-bridgeable in the
#                      standard sense (requires Haar measure, training-process
#                      formalization, or real-data assumptions outside Mathlib)
PAPER_FACING_SORRIES = [
    # NOTE: random_subspace_expected_overlap — PROVEN (2026-04-18, outcome 2 partial):
    #   weakened to deterministic `subspaceOverlap U W ≤ 1`; no longer a paper-facing sorry.
    # NOTE: stable_rank_acoustic_scaling — PROVEN (2026-04-18, outcome 2 partial):
    #   proved under acoustic axioms frobeniusSq=d, spectralSq=√d; no longer a paper-facing sorry.
    (
        "gamma_right_alignment",
        "§4 / §5 (bonus_R ≥ 5× across Pythia suite)",
        "empirical",
        "Empirical observation from trained checkpoints; a formal proof would require "
        "formalizing the LoRA training process and pretraining distribution, which is "
        "outside Mathlib scope. Named as a target theorem; not a proved claim.",
    ),
    (
        "bias_autopsy_separation",
        "§4.4 (99.97% autopsy residual)",
        "empirical",
        "The specific 99.97% residual is empirical (Pythia-410M checkpoints). The "
        "underlying algebra (left-diagonal cannot perturb right-singular vectors) is a "
        "valid research target, but the quantitative claim depends on data facts not "
        "formalizable in Mathlib. Dropped from Lean-supported claims list.",
    ),
    (
        "lower_bound_of_intent",
        "§5 / §6 (central attractor claim)",
        "empirical",
        "Requires formalizing a task-loss functional on parameter space and a local "
        "quadratic bound on the Hessian near the pretrained base. Both are outside "
        "current Mathlib infrastructure. Long-horizon target; not paper-proved.",
    ),
]

lines += [
    "",
    f"% (a) theorems/lemmas with complete proofs of the full claim",
    f"\\newcommand{{\\leanProvenCount}}{{{proven_count}}}",
    f"% (d) theorems proved in a WEAKENED form (WEAKENING NOTE in-file)",
    f"\\newcommand{{\\leanPartialCount}}{{{partial_count}}}",
    f"% (b) True := sorry stubs — literature-terminology placeholders",
    f"% NOTE: \\leanSorryCount = stub count (b), matching main.tex prose",
    f"\\newcommand{{\\leanSorryCount}}{{{stub_count}}}",
    f"% (c) real statements with deferred proof body (honest load-bearing gaps)",
    f"\\newcommand{{\\leanInProofSorryCount}}{{{in_proof_sorry_count}}}",
    f"% backward-compat alias (same as \\leanSorryCount)",
    f"\\newcommand{{\\leanStubCount}}{{{stub_count}}}",
    f"\\newcommand{{\\leanDefCount}}{{{sum(1 for d in decls if d['kind']=='def')}}}",
    "",
    f"% Paper-facing sorry disclosure (3 sorries cited or implied in paper prose)",
    f"% NOTE: random_subspace_expected_overlap + stable_rank_acoustic_scaling PROVEN 2026-04-18",
    f"% See PAPER_FACING_SORRIES in generate_lean_status.py for full notes.",
    f"% planned = provable, formal proof queued",
    f"% empirical = depends on training-process or Haar-measure assumptions; not Lean-bridgeable",
    f"\\newcommand{{\\leanPaperFacingSorryCount}}{{{len(PAPER_FACING_SORRIES)}}}",
    f"\\newcommand{{\\leanPaperFacingPlannedCount}}{{0}}",
    f"\\newcommand{{\\leanPaperFacingEmpiricalCount}}{{{len(PAPER_FACING_SORRIES)}}}",
    "",
]


# Emit a status table
lines += [
    "% Lean theorem status table",
    "\\begin{table}[h]",
    "  \\centering",
    "  \\caption{Formally verified theorems in",
    "  \\texttt{LeanMining/NeuralGeometry/SubspaceOverlap.lean}"
    " (Lean 4 + Mathlib, as of 2026-04-18). Three-way status:"
    " $\\proofCheck$ = complete proof (no \\texttt{sorry});"
    " $\\proofPartial$ = proof of a strictly weaker statement than the"
    " paper-facing claim (see in-file WEAKENING NOTE);"
    " $\\proofSorry$ = real mathematical statement with deferred proof body"
    " (honest load-bearing gap, known proof sketch exists);"
    " $\\proofStub$ = \\texttt{True := sorry} literature-terminology"
    " placeholder (not a mathematical claim, names a concept for downstream"
    " work). Counts: \\leanProvenCount~proven,"
    " \\leanPartialCount~partial,"
    " \\leanInProofSorryCount~deferred, \\leanSorryCount~stubs."
    " \\texttt{random\\_subspace\\_expected\\_overlap} and"
    " \\texttt{stable\\_rank\\_acoustic\\_scaling} were closed 2026-04-18"
    " (weakened deterministic forms; see in-file WEAKENING NOTEs)."
    " Remaining \\leanPaperFacingSorryCount~paper-facing stubs"
    " (\\texttt{gamma\\_right\\_alignment},"
    " \\texttt{bias\\_autopsy\\_separation},"
    " \\texttt{lower\\_bound\\_of\\_intent}):"
    " empirical or aspirational claims not Lean-bridgeable from first principles;"
    " none are cited as proven results.}",
    "  \\label{tab:lean-status}",
    "  \\small",
    "  \\begin{tabular}{ll}",
    "    \\toprule",
    "    Theorem / Lemma & Status \\\\",
    "    \\midrule",
]
for d in decls:
    if d["kind"] not in ("theorem", "lemma"):
        continue
    if d["is_true_stub"]:
        stat = "\\proofStub"
    elif d["has_sorry"]:
        stat = "\\proofSorry"
    elif d["is_partial"]:
        stat = "\\proofPartial"
    else:
        stat = "\\proofCheck"
    disp = d["name"].replace("_", "\\_")
    lines.append(f"    \\texttt{{{disp}}} & {stat} \\\\")
lines += [
    "    \\bottomrule",
    "  \\end{tabular}",
    "\\end{table}",
]

(HERE / "lean_status.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {HERE / 'lean_status.tex'}")
print(f"  proven (a): {proven_count}, deferred/in-proof sorry (c): {in_proof_sorry_count}, stubs/True-sorry (b): {stub_count}")
