"""Generate lean_status.tex: parse SubspaceOverlap.lean, emit theorem-status
macros and a status table.

For each `theorem` / `lemma` / `def` declaration, detect whether the body
contains `sorry`. Emit macros so main.tex can say
"Theorem \thmStatOf{stableRank\_smul\_invariant}" and the current status
flips automatically when the Lean file changes.
"""
from __future__ import annotations
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
LEAN = HERE.parent / "lean" / "SubspaceOverlap.lean"


def parse(src: str) -> list[dict]:
    """Extract (kind, name, has_sorry) for each top-level declaration.
    Heuristic: look for 'theorem X', 'lemma X', 'def X', 'noncomputable def X';
    the declaration extends to the next such keyword or end of file.
    """
    # Tokenize by declaration starts
    pattern = re.compile(
        r"^(?:noncomputable\s+)?(theorem|lemma|def)\s+([A-Za-z_][A-Za-z0-9_']*)",
        re.MULTILINE,
    )
    matches = list(pattern.finditer(src))
    out = []
    for i, m in enumerate(matches):
        kind, name = m.group(1), m.group(2)
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(src)
        body = src[start:end]
        # Detect sorry — but only if it appears as a statement, not in comments/strings.
        # Simple heuristic: strip line comments, then search for "sorry".
        body_code = re.sub(r"--[^\n]*", "", body)
        # Strip block comments (/- ... -/)
        body_code = re.sub(r"/-.*?-/", "", body_code, flags=re.DOTALL)
        has_sorry = bool(re.search(r"\bsorry\b", body_code))
        # Detect True-sorry stubs (trivial theorem placeholders)
        is_true_stub = bool(re.search(r":\s*True\s*:=\s*sorry", body_code))
        out.append({
            "kind": kind,
            "name": name,
            "has_sorry": has_sorry,
            "is_true_stub": is_true_stub,
        })
    return out


src = LEAN.read_text()
decls = parse(src)


def tex_name(name: str) -> str:
    """Convert snake_case to CamelCase for LaTeX macro names.
    Preserve existing camelCase within each underscore-separated segment:
    `frobeniusSq` → `FrobeniusSq` (not `Frobeniussq`)."""
    return "thmStatOf" + "".join(w[:1].upper() + w[1:] for w in name.split("_"))


# Emit per-theorem status macros
lines = [
    "% Auto-generated by generate_lean_status.py — DO NOT EDIT",
    "% Regenerate: make lean-status",
    "",
    "\\newcommand{\\proofCheck}{\\ensuremath{\\checkmark}}",
    "\\newcommand{\\proofSorry}{\\textsc{sorry}}",
    "\\newcommand{\\proofStub}{\\textsc{stub}}",
    "",
]

proven_count = 0
sorry_count = 0
stub_count = 0

for d in decls:
    if d["kind"] in ("theorem", "lemma"):
        if d["is_true_stub"]:
            status_macro = "\\proofStub"
            stub_count += 1
        elif d["has_sorry"]:
            status_macro = "\\proofSorry"
            sorry_count += 1
        else:
            status_macro = "\\proofCheck"
            proven_count += 1
        lines.append(f"\\newcommand{{\\{tex_name(d['name'])}}}{{{status_macro}}}")

lines += [
    "",
    f"\\newcommand{{\\leanProvenCount}}{{{proven_count}}}",
    f"\\newcommand{{\\leanSorryCount}}{{{sorry_count}}}",
    f"\\newcommand{{\\leanStubCount}}{{{stub_count}}}",
    f"\\newcommand{{\\leanDefCount}}{{{sum(1 for d in decls if d['kind']=='def')}}}",
    "",
]


# Emit a status table
lines += [
    "% Lean theorem status table",
    "\\begin{table}[h]",
    "  \\centering",
    "  \\caption{Formally verified theorems in",
    "  \\texttt{LeanMining/NeuralGeometry/SubspaceOverlap.lean}"
    " (Lean 4 + Mathlib). $\\proofCheck$ = complete proof;"
    " $\\proofSorry$ = targeted \\texttt{sorry} (definition or statement"
    " deferred); $\\proofStub$ = literature-terminology placeholder.}",
    "  \\label{tab:lean-status}",
    "  \\small",
    "  \\begin{tabular}{ll}",
    "    \\toprule",
    "    Theorem / Lemma & Status \\\\",
    "    \\midrule",
]
for d in decls:
    if d["kind"] not in ("theorem", "lemma"):
        continue
    stat = "\\proofStub" if d["is_true_stub"] else ("\\proofSorry" if d["has_sorry"] else "\\proofCheck")
    # escape underscores for display
    disp = d["name"].replace("_", "\\_")
    lines.append(f"    \\texttt{{{disp}}} & {stat} \\\\")
lines += [
    "    \\bottomrule",
    "  \\end{tabular}",
    "\\end{table}",
]

(HERE / "lean_status.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {HERE / 'lean_status.tex'}")
print(f"  proven: {proven_count}, sorry: {sorry_count}, stub: {stub_count}")
